#!/usr/bin/env python
"""
PyCopter node. Inits a node and runs a pycopter script
"""
# Global libraries
import argparse
# Third-party libraries
import rospy
# Local libraries
from pycopter import drone_swarm


if __name__ == "__main__":
    # Parse input arguments
    parser = argparse.ArgumentParser()
    parser.add_argument("-p1", "--param1", type=lambda t:abs(float(t)),
                        default=0.0, help="Parameter 1")

    args = parser.parse_args(rospy.myargv()[1:])
    
    rospy.init_node("drome_swarm_sim", anonymous=True)
    rospy.loginfo("Starting PyCopter")
    drone_swarm.main()
