set(_CATKIN_CURRENT_PACKAGE "formation_control")
set(formation_control_VERSION "0.0.0")
set(formation_control_MAINTAINER "job <job@todo.todo>")
set(formation_control_PACKAGE_FORMAT "2")
set(formation_control_BUILD_DEPENDS "roscpp" "rospy" "sensor_msgs" "std_msgs" "message_generation")
set(formation_control_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "sensor_msgs" "std_msgs")
set(formation_control_BUILDTOOL_DEPENDS "catkin")
set(formation_control_BUILDTOOL_EXPORT_DEPENDS )
set(formation_control_EXEC_DEPENDS "roscpp" "rospy" "sensor_msgs" "std_msgs" "message_runtime")
set(formation_control_RUN_DEPENDS "roscpp" "rospy" "sensor_msgs" "std_msgs" "message_runtime")
set(formation_control_TEST_DEPENDS )
set(formation_control_DOC_DEPENDS )
set(formation_control_URL_WEBSITE "")
set(formation_control_URL_BUGTRACKER "")
set(formation_control_URL_REPOSITORY "")
set(formation_control_DEPRECATED "")